name = "SimpleValidations"
uuid = "5ead8e6a-226e-4abd-9fac-4ba193e998ab"
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[weakdeps]
LoggingPolyglot = "211639cc-9b11-4cfd-abc6-8f7477829344"

[extensions]
LoggingPolyglotExt = "LoggingPolyglot"

[compat]
JSON = "0.21"
OrderedCollections = "1.6"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LoggingPolyglot"]